title: Finding edible plants
body: |
  Another elemental thing to know when you venture into a forest or jungle trip is to know what to eat. Your dining choices largely consists on fruits, edible plants, insects and fish. If you don’t have a guidebook about edible plants you should never try to eat a plant you’re unsure of. It’s better to try to find food elsewhere than risk an intoxication.

  These are basic rules to follow when looking for food:

    * Avoid plants with thorns
    * Steer clear of shiny leaves
    * Stay away from plants with leaves in groups of three or with umbrella-shaped flowers
    * If it tastes bitter or soapy, spit it out
    * Avoid beans or plants with seeds inside a pod
    * Avoid plants with milky or discolored sap
    * An almond smell is a warning sign

  The universal edibility test check wheter a plant is edible. Separate the plant into parts and check closely everyone. Place a piece of plant on your skin and wait a few minutes to see if it burns, itches, feels numb. Touch the plant with your lips, and then take a small bite. If there is no reaction, you can assume the part of plant is edible. Try these steps for every part of the plant before eat it.
  ![plant](/plant.jpg#center)
