title: AngelFish
body: |
  # Materials: 
   * a square sheet of paper

  # Steps:
    1.Fold the paper diagonally, with the line of folding starting at a little distance from the corners.
    ![angelfish1](/angelfish1.png#center)

    2.Fold the paper as showed by the arrow. 
    ![angelfish2](/angelfish2.png#center)

    3.Check if the model is properly aligned.
    ![angelfish3](/angelfish3.png#center)

    4.Draw a smiley face and the model is finished.
    ![angelfish4](/angelfish4.png#center)

