title: Mouse
body: |
  # Materials: 
   * a square piece of paper
   * pens

  # Mentions:
   The blue side of the paper represents the back side, the yellow side represents the front side.

  # Steps:
    1.Start with the back side up, then fold along the shown crease.
    ![mouse1](/mouse1.jpg#center)

    2.Fold again along the crease, as shown by the arrow.
    ![mouse2](/mouse2.jpg#center)

    3.Fold both sides upwards.
    ![mouse3](/mouse3.jpg#center)

    4.Turn the model over.
    ![mouse4](/mouse4.jpg#center)

    5.Draw a face on the model.
    ![mouse5](/mouse5.jpg#center)

    6.Mouse finished!
    ![mouse6](/mouse6.jpg#center)
    
