title: The Power of Four
body: >
  The beauty of this trick comes from its simplicity, because it can be performed at any time, everywhere and
  without any kind preparation or setup, the only prerequisite is a standard 52-cards deck.


  ### Description

  First let`s see what this trick is all about!

  1.  The performer shuffles the cards, or gives them to a spectator to shuffle, it appears as this step is not 
  of great importance.

  2.  The performer shows the public the deck of cards, so that they can see that it is an ordinary shuffled deck 
  and shuffles them again.

  3.  The performer asks a spectator to cut the cards wherever they like.

  4.  Now the performer picks one of the two stacks of cards, and just by looking at the fourth card of the 
  stack, he/she can tell what will be the fourth card in the other stack! And it works every time! 


  Magical right? Well, one might think there is a mathematical explanation behind this, some sort of 
  equation describing the type of a card by the position of another card symmetrically placed in the deck. 
  This sounds about right, except it`s not, it is waaay easyer than this! 


  ### Explanation

  Let`s dissect this card trick step by step!


  1.  As a performer, you will have to shuffle the cards or to give them to shuffle to somebody from your 
  audience to gain their trust.

  2.  To even furher gain the public`s confidence you need to show them the shuffled deck, so that they can see 
  that you have a normal shuffled deck of 52 cards. At least that is what you want your public to think, because in 
  fact what you will really be doing is look at the fourth card in your deck! This is the most important step of 
  this trick, and you should do it in a sneaky way, not obviously staring at the card. If you want, you can 
  mix the deck one again, but just leave the first four cards on top, this way the fourth card will be the same 
  that you saw before, and everybody will just think that the deck is now crazily shuffled!

  ![cards](/powerfour.jpg#center)


  3.  Next you have to ask a spectator to cut the deck in half, wherever they want, giving them a sensation of 
  control over the outcome of the trick.

  4.  This is the last step, where all the "magic" happens! Just look at the fourth card of the second part of the 
  newly split deck. Just stare at it for a little bit, pretending to do some calculations, then just "guess" 
  the fourth card of the other pile, and show the public the card, or ask someone to look at it, again, giving 
  control to the spectators. Aaaand boom! Everybody is shocked of the reveal!


  A cool way to trick your friends, right?

  This card trick was named "The Power of Four" by its creator, but it works with any other number small 
  enough to keep the first "n" cards in the same position when reshuffling.
